export * from "./01-splash/splash"
export * from './01.1-onboarding/onboarding'
export * from "./02-login/login"
export * from "./03-signUp/signUp"
export * from './04-reset-password/reset-password'
export * from './05-oder-check/oder-check'
export * from './06-product/product'
export * from './07-create-product/create-product'
export * from './08-edit-product/edit-product'
export * from './09-categories/categories'
export * from './10-create-category/create-category'
export * from './11-map-category/map-categories'
export * from './12-edit-category/edit-category'